spring:
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: recreate
      local-datacenter: datacenter1
      username: tacoCloudUsername
      password: tacoCloudPassword
      port: 9042
  thymeleaf:
    cache: false
