spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: Taco-Cloud
#    url: jdbc:h2:mem:tacocloud
    username: username
    password: password
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/tacocloud
